services:
  postgres:
    image: postgres:16
    container_name: aurora_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: aurora_marketplace
      POSTGRES_USER: aurora_user
      POSTGRES_PASSWORD: aurora_password
    ports:
      - "5433:5432"
    volumes:
      - aurora_postgres_data:/var/lib/postgresql/data
    networks:
      - aurora_network

  redis:
    image: redis:7-alpine
    container_name: aurora_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - aurora_network

  minio:
    image: minio/minio:latest
    container_name: aurora_minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: aurora_minio
      MINIO_ROOT_PASSWORD: aurora_minio_password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - aurora_minio_data:/data
    networks:
      - aurora_network

  mailpit:
    image: axllent/mailpit:latest
    container_name: aurora_mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - aurora_network

volumes:
  aurora_postgres_data:
  aurora_minio_data:

networks:
  aurora_network:
    driver: bridge
