package com.aurora.backend.audit.entity;

public enum AuditEventType {
    ORDER_CREATED,
    ORDER_STATUS_CHANGED,
    PAYMENT_SIMULATED_SUCCESS,
    PAYMENT_SIMULATED_FAILED,
    COUPON_USED,
    ACCOUNT_LOCKED,
    LOGOUT,
    REFRESH_TOKEN_REUSED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET,
    EMAIL_VERIFICATION_REQUESTED,
    EMAIL_VERIFIED,
    MFA_ENABLED,
    MFA_DISABLED,
    MFA_CHALLENGE_ISSUED,
    MFA_LOGIN_SUCCEEDED
}
